### ISSUE TITLE
File Splitter - UX recommendation

### ISSUE THREAD

**Issue by veler** [adensW/DevToysExtensions#1]
Hello,
Thanks for creating the `File Spliter` extension for DevToys. I have a few recommendations for improvement, if that's OK.

1. If I'm not wrong (English isn't my first language), "Spliter" has 2 "t". So it should be `File Splitter`.
2. You can use the `FileSelector` UI component instead of a `SingleLineTextInput` for the `File path`: https://devtoys.app/doc/articles/extension-development/guidelines/UX/basic-input/file-selector.html
3. Similarly, to set the output file path, you can potentially use the `PickSaveFileAsync` or `PickFolderAsync` method. See: https://devtoys.app/doc/articles/extension-development/guidelines/use-files.html
4. Finally, for the status (splitting in progress, done...etc), you can use ProgressRing, ProgressBar and InfoBar: 
    - https://devtoys.app/doc/articles/extension-development/guidelines/UX/status-info/progress-ring.html
    - https://devtoys.app/doc/articles/extension-development/guidelines/UX/status-info/progress-bar.html
    - https://devtoys.app/doc/articles/extension-development/guidelines/UX/status-info/info-bar.html

Hopefully this can help making the experience more consistent with other tools :-)

Have a wonderful day!

**Comment by adensW** [comment]
Thx for the advice.I will work on improving this.

**Comment by adensW** [comment]
close as complete
