### ISSUE TITLE
Rsa Generator - UX Improvement

### ISSUE THREAD

**Issue by veler** [adensW/DevToysExtensions#2]
Hello again,

Thank you for making the RSA Generator tool! It works great :D

I noticed the MultipleLineTextInput are missing a title. Is it on purpose?
![image](https://github.com/adensW/DevToysExtensions/assets/3747805/527350a3-4ede-4c61-b68d-49be4e063abe)

Also, have you considered using SplitGrid in order to make the text box resizable?
https://devtoys.app/doc/articles/extension-development/guidelines/UX/layout/split-grid.html

Thanks!

**Comment by adensW** [comment]
close as complete
