### ISSUE TITLE
RsaGenerator - key length input above some value hangs UI

### ISSUE THREAD

**Issue by TilKenneth** [adensW/DevToysExtensions#4]
Inputting say 16384 or 14336 hangs the UI and give the window "Not Responding"-effect if interacted with.

Suggestion to add "Are you sure you want this key length, this length"... something about whats happening.

I did wait out key length of 12288 (2048*6), and 16384 (took "quite abit") - so it was just working, which is why I am here.

Maybe add a Benchmark for up to... 1024*1, 1024*2, 1024*4, maybe 1024*6? , in TimeSpan so it maybe is more predictable for the user?

Thanks for the extension!

**Comment by adensW** [comment]
I did some benchmarks. You can check the readme for RSA Generator [here](https://github.com/adensW/DevToysExtensions/blob/main/doc/RsaGenerator.md)
At the same time, it will prompt whether to generate the length greater than 8092.

**Comment by TilKenneth** [comment]
After 2 hours of tinkering with benchmarkdotnet I gave up, but I managed to get these results, I commented out some of the other tests in the code.

```text
// * Summary *

BenchmarkDotNet v0.14.0, Windows 11 (10.0.22631.4317/23H2/2023Update/SunValley3)
12th Gen Intel Core i7-12700H, 1 CPU, 20 logical and 14 physical cores
.NET SDK 8.0.403
  [Host]     : .NET 8.0.10 (8.0.1024.46610), X64 RyuJIT AVX2
  DefaultJob : .NET 8.0.10 (8.0.1024.46610), X64 RyuJIT AVX2


| Method   | Mean         | Error        | StdDev      | Median       |
|--------- |-------------:|-------------:|------------:|-------------:|
| Key2048  |     68.12 ms |     9.476 ms |    27.94 ms |     54.46 ms |
| Key4096  |    526.94 ms |    71.393 ms |   209.38 ms |    472.67 ms |
| Key6144  |  2,058.21 ms |   315.529 ms |   905.31 ms |  1,803.78 ms |
| Key8192  |  5,144.07 ms |   714.556 ms | 2,061.66 ms |  4,734.25 ms |
| Key10240 | 14,542.85 ms | 2,454.328 ms | 7,159.39 ms | 13,023.69 ms |

// * Legends *
  Mean   : Arithmetic mean of all measurements
  Error  : Half of 99.9% confidence interval
  StdDev : Standard deviation of all measurements
  Median : Value separating the higher half of all measurements (50th percentile)
  1 ms   : 1 Millisecond (0.001 sec)

// ***** BenchmarkRunner: End *****
Run time: 00:43:52 (2632.28 sec), executed benchmarks: 5

Global total time: 00:43:59 (2639.33 sec), executed benchmarks: 5
```
Attaching the "md" report.

[Adens.DevToys.RsaGenerator.Benchmarks.Program.RsaGeneratorBenchmark-report-github.md](https://github.com/user-attachments/files/17523749/Adens.DevToys.RsaGenerator.Benchmarks.Program.RsaGeneratorBenchmark-report-github.md)
